name: bunny_sync
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.10+10

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  animated_size_and_fade:
    git: https://github.com/MohamadGreatWarrior/animated_size_and_fade.git

  auto_route: ^8.1.3

  auto_size_text: ^3.0.0
  bloc: ^8.1.2

  cached_network_image: ^3.2.3

  collection: ^1.17.1

  copy_with_extension: ^5.0.4

  cupertino_icons: ^1.0.6

  dart_code_metrics: ^5.7.6

  data_table_2: ^2.5.15
  dio: ^5.3.2

  dropdown_button2: ^2.3.9
  email_validator: ^2.1.17

  equatable: ^2.0.5

  file_picker: ^8.0.6
  flash: ^3.0.5+1

  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3

  flutter_holo_date_picker: ^1.1.3
  flutter_native_splash: ^2.4.0

  flutter_screenutil: ^5.8.4

  flutter_secure_storage: ^9.0.0

  flutter_spinkit: ^5.2.0

  flutter_staggered_animations: ^1.1.1

  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.7

  fluttertoast: ^8.2.8
  get_it: ^7.6.0

  gettext_parser: ^0.2.0

  google_fonts: ^4.0.4

  i18n_extension: ^10.0.3

  image_picker: ^1.1.2

  injectable: ^2.3.0

  intl: ^0.18.1

  json_annotation: ^4.8.1

  lint: ^2.1.2

  loader_overlay: ^4.0.1

  logger: ^2.0.1

  meta: ^1.9.1

  mobile_scanner: ^5.1.1

  modal_bottom_sheet: ^3.0.0

  moment_dart: ^2.1.0

  permission_handler: ^11.3.1

  pretty_dio_logger: ^1.3.1

  scroll_date_picker: ^3.8.0

  shared_preferences: ^2.2.0

  shimmer: ^3.0.0

  skeletonizer: ^1.3.0

  smooth_page_indicator: ^1.1.0

  syncfusion_flutter_datepicker: ^26.1.39

  theme_tailor_annotation: ^2.0.0

  tuple: ^2.0.2

  url_launcher: ^6.2.6

dev_dependencies:
  auto_route_generator: ^8.0.0

  build_runner: ^2.4.6

  copy_with_extension_gen: ^5.0.4

  flutter_lints: ^4.0.0

  flutter_test:
    sdk: flutter

  injectable_generator: ^2.4.0

  json_serializable: ^6.7.1

  theme_tailor: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/locales/

flutter_gen:
  output: lib/global/gen/

  integrations:
    flutter_svg: true

scripts:
  inspect: dart format . & flutter analyze

  clean: flutter clean ; flutter packages get

  build: dart run build_runner build --delete-conflicting-outputs

  watch: dart run build_runner watch --delete-conflicting-outputs

  splash: dart run flutter_native_splash:create