import 'package:bunny_sync/features/litters/models/litter_entry_model/litter_entry_model.dart';
import 'package:bunny_sync/features/litters/models/litters_model/litters_model.dart';
import 'package:bunny_sync/features/litters/models/litters_status_model/litters_status_model.dart';

final fakeLittersStatusModel = LittersStatusModel(
  all: fakeLittersModel.litters,
  active: fakeLittersModel.litters,
  inactive: fakeLittersModel.litters,
);

final fakeLittersModel = LittersModel(
  draw: 0,
  recordsTotal: 1,
  recordsFiltered: 1,
  litters: [
    LitterEntryModel(
      id: 1,
      userId: 1,
      breedPairId: 1,
      litterId: '1',
      type: 'type',
      prefix: 'prefix',
      breed: 'breed',
      born: 'born',
      cage: 'cage',
      breedText: 'breedText',
      status: 'active',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      buck: 'buck',
      buckImage: 'buckImage',
      doe: 'doe',
      doeImage: 'doeImage',
      age: 'age',
      kits: 3,
      live: 3,
      dead: 0,
      sold: '',
      dtRowIndex: 1,
      isActive: true,
    ),
    LitterEntryModel(
      id: 1,
      userId: 1,
      breedPairId: 1,
      litterId: '1',
      type: 'type',
      prefix: 'prefix',
      breed: 'breed',
      born: 'born',
      cage: 'cage',
      breedText: 'breedText',
      status: 'active',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      buck: 'buck',
      buckImage: 'buckImage',
      doe: 'doe',
      doeImage: 'doeImage',
      age: 'age',
      kits: 3,
      live: 3,
      dead: 0,
      sold: '',
      dtRowIndex: 1,
      isActive: true,
    ),
    LitterEntryModel(
      id: 1,
      userId: 1,
      breedPairId: 1,
      litterId: '1',
      type: 'type',
      prefix: 'prefix',
      breed: 'breed',
      born: 'born',
      cage: 'cage',
      breedText: 'breedText',
      status: 'active',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      buck: 'buck',
      buckImage: 'buckImage',
      doe: 'doe',
      doeImage: 'doeImage',
      age: 'age',
      kits: 3,
      live: 3,
      dead: 0,
      sold: '',
      dtRowIndex: 1,
      isActive: true,
    ),
  ],
  input: const [],
);
