import 'package:bunny_sync/features/breeders/models/breeder_model/breeder_model.dart';
import 'package:bunny_sync/features/breeders/models/breeders_model/breeders_model.dart';

final fakeBreedersModel = BreedersModel(
  draw: 0,
  recordsTotal: 10,
  recordsFiltered: 10,
  breeders: [
    BreederModel(
      id: 1,
      userId: 1,
      uuid: 'uuid 1',
      updatedAt: DateTime.now(),
      createdAt: DateTime.now(),
      name: 'Breeder 1',
      prefix: 'Prefix 1',
      cage: 'Cage 1',
      weight: '1.0',
      litters: '10',
      kits: '10',
      age: '10',
      status: 'Status 1',
      photo: 'Photo 1',
      dtRowIndex: 1,
    ),
    BreederModel(
      id: 1,
      userId: 1,
      uuid: 'uuid 1',
      updatedAt: DateTime.now(),
      createdAt: DateTime.now(),
      name: 'Breeder 1',
      prefix: 'Prefix 1',
      cage: 'Cage 1',
      weight: '1.0',
      litters: '10',
      kits: '10',
      age: '10',
      status: 'Status 1',
      photo: 'Photo 1',
      dtRowIndex: 1,
    ),
    BreederModel(
      id: 1,
      userId: 1,
      uuid: 'uuid 1',
      updatedAt: DateTime.now(),
      createdAt: DateTime.now(),
      name: 'Breeder 1',
      prefix: 'Prefix 1',
      cage: 'Cage 1',
      weight: '1.0',
      litters: '10',
      kits: '10',
      age: '10',
      status: 'Status 1',
      photo: 'Photo 1',
      dtRowIndex: 1,
    ),
  ],
  input: const [],
);
